#!/bin/sh
#	
while true 
do
    declare -i powint
    declare -i limit
    blink=0
    limit=30
    full=`cat /proc/acpi/battery/BAT0/info | awk '/design capacity:/ {print$3}'`
    if [ -S ~/.awesome_ctl.0 ]; then
        while true
        do
	    ac=`cat /proc/acpi/ac_adapter/AC/state | awk '/state/ {print$2}'`
	    ol='on-line'
	    cur=`cat /proc/acpi/battery/BAT0/state | awk '/remaining capacity:/ {print$3}'`
	    power=`echo ${cur} ${full} | awk '{printf "%.1f", $1/$2 * 100}'`
	    powint=`echo ${power} | cut -d . -f 1`
	    if [ ${ac} = ${ol} ]; then
		echo "0 widget_tell mystatusbar battery fg bat #3388cc"
                echo "0 widget_tell mystatusbar battery bordercolor bat #000000"
		echo "0 widget_tell mystatusbar battery data bat ${power}"
	    else	  
		if [ ${powint} -lt ${limit} ]; then
		    echo "0 widget_tell mystatusbar battery fg bat #ff4500"                 
                    if [ ${blink} == 1 ]; then
                        echo "0 widget_tell mystatusbar battery bordercolor bat #000000"
                        blink=0
                    else
                        echo "0 widget_tell mystatusbar battery bordercolor bat #ff4500"
                        blink=1
                    fi
		else
		    echo "0 widget_tell mystatusbar battery fg bat #33ff44"
                    blink=0
		fi
		echo "0 widget_tell mystatusbar battery data bat ${power}"
	    fi
            echo "" # an empty line flushes data inside awesome
            sleep 1
        done | awesome-client
    else
        sleep 1
    fi
done
